Aditional path info for groovy config load
bcgov/supreme-court-viewer-configurations pull request #25
Opened 2023-05-08 20:58 UTC by nikola-rados

Changes:
- add extra path info to `Jenkinsfile`

This change addresses the [build error](https://jenkins-90a666-tools.apps.silver.devops.gov.bc.ca/job/90a666-tools/job/90a666-tools-build-pipeline/379/console) found in the Jenkins build pipeline. This issue is similar to one we have seen in the past with other [applications](https://github.com/bcgov/representation-grant-app/blob/main/jenkins/api/Jenkinsfile#L125).

2023-05-09 13:53 UTC, WadeBarnes requested changes
You should switch to a more reliable pattern for loading the `config.groovy` file.

Example here:
- https://github.com/bcgov/von-bc-registries-agent-configurations/blob/main/jenkins/agent/Jenkinsfile#L13-L20
- https://github.com/bcgov/von-bc-registries-agent-configurations/commit/127e7c1d1ba22df9146f69e6458c3978a5405021

2023-05-11 20:46 UTC, nikola-rados commented
@WadeBarnes do you know if this stage would still need to reference that hash before `/jenkins`? Or is it going to capture that context?

2023-05-12 12:22 UTC, WadeBarnes commented
> @WadeBarnes do you know if this stage would still need to reference that hash before `/jenkins`? Or is it going to capture that context?

It's checking out a copy of the repo and loading the settings from there.  No need for the hash.

2023-05-12 12:22 UTC, WadeBarnes approved these changes

2025-09-05 22:12 UTC, nikola-rados commented
Don't think this is going to get merged... sorry @WadeBarnes 😆 I'll go ahead and close it.

2025-09-05 22:12 UTC, closed without merging